# Generated by Django 5.2.4 on 2025-07-30 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dim_Customers",
            fields=[
                ("CustomerID", models.IntegerField(primary_key=True, serialize=False)),
                ("Country", models.CharField(blank=True, max_length=100, null=True)),
                ("District", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "Customer_TotalSpending",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("Segment", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dim_Products",
            fields=[
                (
                    "StockCode",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("Description", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "Description_Categorize",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fact_Transactions",
            fields=[
                (
                    "InvoiceNo",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("Quantity", models.IntegerField()),
                ("UnitPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("TotalPrice", models.DecimalField(decimal_places=2, max_digits=12)),
                ("InvoiceDate", models.DateTimeField()),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommendations.dim_customers",
                    ),
                ),
                (
                    "StockCode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommendations.dim_products",
                    ),
                ),
            ],
        ),
    ]
