# Generated by Django 5.2.4 on 2025-07-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dim_Customer',
            new_name='Dim_Customers',
        ),
        migrations.RenameModel(
            old_name='Dim_Product',
            new_name='Dim_Products',
        ),
        migrations.RenameModel(
            old_name='Fact_Transaction',
            new_name='Fact_Transactions',
        ),
    ]
